"""updated QA and Document models

Revision ID: 9997f047f28c
Revises: dfd9336b6da5
Create Date: 2025-08-01 10:17:35.718717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9997f047f28c'
down_revision: Union[str, Sequence[str], None] = 'dfd9336b6da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_logs', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_question_doc', 'qa_logs', ['question', 'document_id'])
    op.create_foreign_key(None, 'qa_logs', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qa_logs', type_='foreignkey')
    op.drop_constraint('uq_question_doc', 'qa_logs', type_='unique')
    op.alter_column('qa_logs', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
